# Generated by Django 4.2.4 on 2023-08-15 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import room.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=50)),
                ('Image', models.ImageField(upload_to='photos/rooms')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
